### ISSUE TITLE
add_ranks

### ISSUE THREAD

**Issue by laurenmh** [mavolio/RACs#12]
add_ranks_replicate:
- [ ] decide if this should be exported
- [ ] if we do export: add examples and a better description, if we don't delete @export
- [ ] pull out the S function, etc to its own file as it is used in multiple functions
- [ ] similarly, move all the private functions in this script to utilities in codyn

add_ranks_time:
- [ ] decide if this should be exported
- [ ] if we do export: add examples and a better description, if we don't delete @export
- [ ] pull out the S function, etc to its own file as it is used in multiple functions
- [ ] similarly, move all the private functions in this script to utilities in codyn

**Comment by laurenmh** [comment]
PS - I don't totally understand the difference between these two functions, could it be one generic one where people could chose time or replicate?

**Comment by itcarroll** [comment]
copied to mavolio/codyn
