### ISSUE TITLE
Correct the if statements for functions with metrics

### ISSUE THREAD

**Issue by laurenmh** [mavolio/RACs#17]
Instead of ifelse use a series of ifs that use the specific metric names
This needs to be corrected on at least:

- [ ] community_diversity

- [ ] community_structure

**Comment by laurenmh** [comment]
Similarly, might update the metric argument to always be "metric" rather than "diversity" or "evenness" to parallel existing codyn

**Comment by itcarroll** [comment]
copied to mavolio/codyn
