### ISSUE TITLE
RAC_change consecutive years issue

### ISSUE THREAD

**Issue by laurenmh** [mavolio/RACs#2]
Merging by year and year plus one is the problem because it drops any years that are not consecutive when we shifted to lapply and not the loop

**Comment by laurenmh** [comment]
When we re-run the functions for the CoDyn dataset (with all the issues) and the simulated data (which is perfect), it works for the simulated and not for CoDyn

**Comment by laurenmh** [comment]
will also need to be fixed in species abundance change

**Comment by laurenmh** [comment]
if we need to go back to a loop, it is fast for curve change and not for RAC

**Comment by mavolio** [comment]
After Lauren's fix, I fixed the time-pair.  Also fixed both (time-pair, and not consecutive years) problem in abundance_change.
