### ISSUE TITLE
multivariate_change

### ISSUE THREAD

**Issue by laurenmh** [mavolio/RACs#3]
When we put in plotID instead of the ID it says it can't find experiment_year even when we are very clear that time.var = experiment_year 

it says that it can't find the object experiment_year

**Comment by laurenmh** [comment]
When you give it ID instead plotID there is a different error that is x has to be numeric (it is trying to sum something that isn't numeric)

rowSums is not a part of the function, so need to find which dependent function is using it and what is happening. Probably a vegan thing because we are using vegdist

**Comment by mavolio** [comment]
Okay. I fixed the first part with saying it cannot find experiment_year.

**Comment by mavolio** [comment]
this is fixed and works. and the time-pair is also correct
