### ISSUE TITLE
abundance_difference

### ISSUE THREAD

**Issue by laurenmh** [mavolio/RACs#9]
- [ ] need to add a description for the function
- [ ] check to make sure the columns returned are correct
- [ ] need to find and fix the section that assigns abund_diff instead of abundance.var_diff
- [ ] need to add an example to the documentation
- [ ] add documentation to the private functions
- [ ] make the description of the abund_diff column more specific 
- [ ] add details to the documentation if apppropriate

**Comment by itcarroll** [comment]
copied to mavolio/codyn
